export const placeholderData = 
[
    {  
        "ListName": "FinanceAppMaterialData",
        "ItemId": 1,
        "Year": 2017,
        "State": "create",
        "Highlights": [],   
        "Mat":"Printing Graphics",
        "MatBudget": 0,
        "MatJan": 0,
        "MatFeb":0,
        "MatMar":0,
        "MatApr":0,
        "MatMay":0,
        "MatJun":0,
        "MatJul":0,
        "MatAug":0,
        "MatSep":0,
        "MatOct":0,
        "MatNov":0,
        "MatDec":0,
        "MatYtdTotal":0,
        "MatLbe":741,
        "MatYtdVarianceToBudget":0,
        "MatVarianceToBudget":0
    },
    {  
        "ListName": "FinanceAppMaterialData",
        "ItemId": 1,
        "Year": 2017,
        "State": "create",
        "Highlights": [],   
        "Mat":"Training Room",
        "MatBudget": 0,
        "MatJan": 0,
        "MatFeb":0,
        "MatMar":0,
        "MatApr":0,
        "MatMay":0,
        "MatJun":0,
        "MatJul":0,
        "MatAug":0,
        "MatSep":0,
        "MatOct":0,
        "MatNov":0,
        "MatDec":0,
        "MatYtdTotal":0,
        "MatLbe":541,
        "MatYtdVarianceToBudget":0,
        "MatVarianceToBudget":0
    },
    {  
        "ListName": "FinanceAppMaterialData",
        "ItemId": 1,
        "Year": 2017,
        "State": "create",
        "Highlights": [],   
        "Mat":"Office Party drinks",
        "MatBudget": 0,
        "MatJan": 0,
        "MatFeb":0,
        "MatMar":0,
        "MatApr":0,
        "MatMay":0,
        "MatJun":0,
        "MatJul":0,
        "MatAug":0,
        "MatSep":0,
        "MatOct":0,
        "MatNov":0,
        "MatDec":0,
        "MatYtdTotal":0,
        "MatLbe":454,
        "MatYtdVarianceToBudget":0,
        "MatVarianceToBudget":0
    }, 
    {  
        "ListName": "FinanceAppMaterialData",
        "ItemId": 1,
        "Year": 2017,
        "State": "create",
        "Highlights": [],   
        "Mat":"Servers",
        "MatBudget": 0,
        "MatJan": 0,
        "MatFeb":0,
        "MatMar":0,
        "MatApr":0,
        "MatMay":0,
        "MatJun":0,
        "MatJul":0,
        "MatAug":0,
        "MatSep":0,
        "MatOct":0,
        "MatNov":0,
        "MatDec":0,
        "MatYtdTotal":0,
        "MatLbe":4871,
        "MatYtdVarianceToBudget":0,
        "MatVarianceToBudget":0
    }, 
    {  
        "ListName": "FinanceAppMaterialData",
        "ItemId": 1,
        "Year": 2017,
        "State": "create",
        "Highlights": [],   
        "Mat":"Licences",
        "MatBudget": 0,
        "MatJan": 0,
        "MatFeb":0,
        "MatMar":0,
        "MatApr":0,
        "MatMay":0,
        "MatJun":0,
        "MatJul":0,
        "MatAug":0,
        "MatSep":0,
        "MatOct":0,
        "MatNov":0,
        "MatDec":0,
        "MatYtdTotal":0,
        "MatLbe":5871,
        "MatYtdVarianceToBudget":0,
        "MatVarianceToBudget":0
    }, 
    {  
        "ListName": "FinanceAppMaterialData",
        "ItemId": 1,
        "Year": 2017,
        "State": "create",
        "Highlights": [],   
        "Mat":"venue",
        "MatBudget": 0,
        "MatJan": 0,
        "MatFeb":0,
        "MatMar":0,
        "MatApr":0,
        "MatMay":0,
        "MatJun":0,
        "MatJul":0,
        "MatAug":0,
        "MatSep":0,
        "MatOct":0,
        "MatNov":0,
        "MatDec":0,
        "MatYtdTotal":0,
        "MatLbe":3282,
        "MatYtdVarianceToBudget":0,
        "MatVarianceToBudget":0
    }, 
    {  
        "ListName": "FinanceAppMaterialData",
        "ItemId": 1,
        "Year": 2017,
        "State": "create",
        "Highlights": [],   
        "Mat":"Photocopying",
        "MatBudget": 0,
        "MatJan": 0,
        "MatFeb":0,
        "MatMar":0,
        "MatApr":0,
        "MatMay":0,
        "MatJun":0,
        "MatJul":0,
        "MatAug":0,
        "MatSep":0,
        "MatOct":0,
        "MatNov":0,
        "MatDec":0,
        "MatYtdTotal":0,
        "MatLbe":44,
        "MatYtdVarianceToBudget":0,
        "MatVarianceToBudget":0
    }                       
 
]

export const configData = {

}