export interface IMatModel {
    ListName: string,
    ItemId: number,
    ID: number,
    Year: number,
    State: string,
    Highlights: Array<any>, 
    Mat: string,
    MatBudget: number,
    MatJan: number,
    MatFeb: number,
    MatMar: number,
    MatApr: number,
    MatMay: number,
    MatJun: number,
    MatJul: number,
    MatAug: number,
    MatSep: number,
    MatOct: number,
    MatNov: number,
    MatDec: number,
    MatYtdTotal: number,
    MatLbe: number,
    MatYtdVarianceToBudget: number,
    MatVarianceToBudget:number    
}