export interface IResourceModel {
          ListName: string,
          ID: number,
          ItemId: number,
          Year: number,
          State: string,
          Highlights: Array<any>, 
          Role: string,
          Name: string,
          ContractedDayHours: number,
          PUJan: number,
          PUFeb: number,
          PUMar: number,
          PUApr: number,
          PUMay: number,
          PUJun: number,
          PUJul: number,
          PUAug: number,
          PUSep: number,
          PUOct: number,
          PUNov: number,
          PUDec: number,
          PUForecast: number,
          AHJan: number,
          AHFeb: number,
          AHMar: number,
          AHApr: number,
          AHMay: number,
          AHJun: number,
          AHJul: number,
          AHAug: number,
          AHSep: number,
          AHOct: number,
          AHNov: number,
          AHDec: number,
          AHTotalHours: number,
          AHOverHours: number,
          PRDayRate: number,
          PRBudget: number,
          PRJan: number,
          PRFeb: number,
          PRMar: number,
          PRApr: number,
          PRMay: number,
          PRJun: number,
          PRJul: number,
          PRAug: number,
          PRSep: number,
          PROct: number,
          PRNov: number,
          PRDec: number,
          PRYtdTotal: number,
          PRLbe: number,
          PRYtdVarianceToBudget: number,
          PRForecastVarianceToBudget: number,
          TSDayRate: number,
          TSJan: number,
          TSFeb: number,
          TSMar: number,
          TSApr: number,
          TSMay: number,
          TSJun: number,
          TSJul: number,
          TSAug: number,
          TSSep: number,
          TSOct: number,
          TSNov: number,
          TSDec: number,
          TSForecast: number,
          ATSJan: number,
          ATSFeb: number,
          ATSMar: number,
          ATSApr: number,
          ATSMay: number,
          ATSJun: number,
          ATSJul: number,
          ATSAug: number,
          ATSSep: number,
          ATSOct: number,
          ATSNov: number,
          ATSDec: number,
          ATSYtdTotal: number,
          RTSBudget: number,
          RTSJan: number, 
          RTSFeb: number,
          RTSMar: number,
          RTSApr: number,
          RTSMay: number,
          RTSJun: number,
          RTSJul: number,
          RTSAug: number,
          RTSSep: number,
          RTSOct: number,
          RTSNov: number,
          RTSDec: number,
          RTSYtdTotal: number,
          RTSLbe: number,
          RTSYtdVarianceToBudget: number,
          RTSVarianceToBudget: number,
        //   Mat: string,
        //   MatBudget: number,
        //   MatJan: number,
        //   MatFeb: number,
        //   MatMar: number,
        //   MatApr: number,
        //   MatMay: number,
        //   MatJun: number,
        //   MatJul: number,
        //   MatAug: number,
        //   MatSep: number,
        //   MatOct: number,
        //   MatNov: number,
        //   MatDec: number,
        //   MatYtdTotal: number,
        //   MatLbe: number,
        //   MatYtdVarianceToBudget: number,
        //   MatVarianceToBudget:number

}