export interface ISummaryModel {
    ListName: string,
    Year: number,
    ID: number,
    ItemId: number,
    State: string,
    CostBaseline: number,
    CostLbe: number,
    CostYtd: number,
    CostVariance: number,
    CostVairancePercentage: number,
    CostRag: number,
    GrossBenefitBaseline: number,
    GrossBenefitLbe: number,
    GrossBenefitYtd: number,
    GrossBenefitVariance: number,
    GrossBenefitVariancePercentage: number,
    GrossRag: number,
    NetBenefitBaseline: number,
    NetBenefitLbe: number,
    NetBenefitYtd: number,
    NetBenefitVariance: number,
    NetBenefitVariancePercentage: number,
    NetRag: number
}
