export const placeholderData = [
    {
        "ListName": "FinanceAppTotalsData",
        "ItemId": 1,
        "Year": 2017,
        "State": "create",
        "Highlights": [],
        "Placeholder1":"TOTAL (Incl Resource Costs)",
        "PRBudget":0,
        "PRJan": 4521,
        "PRFeb":5874,
        "PRMar": 4121,
        "PRApr": 3658,
        "PRMay": 5478,
        "PRJun": 6321,
        "PRJul": 8745,
        "PRAug": 2142,
        "PRSep": 4125,
        "PROct": 6547,
        "PRNov": 3254,
        "PRDec": 4574,
        "PRYtdTotal": 1,
        "PRLbe": 55413,
        "PRYtdVarianceToBudget": 1,
        "PRForecastVarianceToBudget": 1,
        "RTSBudget": 1,
        "RTSJan": 1211,
        "RTSFeb": 1547,
        "RTSMar": 2345,
        "RTSApr": 987,
        "RTSMay": 1453,
        "RTSJun": 1874,
        "RTSJul": 1654,
        "RTSAug": 1475,
        "RTSSep": 1965,
        "RTSOct": 1124,
        "RTSNov": 1311,
        "RTSDec": 874,
        "RTSYtdTotal": 1,
        "RTSLbe": 2100,
        "RTSYtdVarianceToBudget": 0,
        "RTSVarianceToBudget": 0,
        "MatBudget": 0,
        "MatJan": 254,
        "MatFeb": 265,
        "MatMar": 276,
        "MatApr": 283,
        "MatMay": 294,
        "MatJun": 303,
        "MatJul": 312,
        "MatAug": 323,
        "MatSep": 332,
        "MatOct": 343,
        "MatNov": 351,
        "MatDec": 365,
        "MatYtdTotal": 0,
        "MatLbe": 4512,
        "MatYtdVarianceToBudget": 0,
        "MatForecastVarianceToBudget": 0,
        "TProjectBudget":0,
        "TJan":0,
        "TFeb":0,
        "TMar":0,
        "TApr":0,
        "TMay":0,
        "TJun":0,
        "TJul":0,
        "TAug":0,
        "TSep":0,
        "TOct":0,
        "TNov":0,
        "TDec":0,
        "TYtdTotal":0,
        "TLbe":0,
        "TYtdVarianceToBudget":0,
        "TVarianceToBudget":0,
        "Placeholder4": "Resource Totals",
        "Placeholder5": "Resource T&S Totals",
        "Placeholder6": "Material Totals"
    }
]


export const stackConfig = {
    
}
