import { IMatModel } from  '../model/material.model'

export const initMaterialData: IMatModel[] = [
 {  
    ListName: 'FinanceAppMaterialData',
    ItemId: 1,
    Year: 2017,
    State: 'create',
    Highlights: [],   
    Mat:'<PLACEHOLDER>',
    MatBudget: 0,
    MatJan: 0,
    MatFeb:0,
    MatMar:0,
    MatApr:0,
    MatMay:0,
    MatJun:0,
    MatJul:0,
    MatAug:0,
    MatSep:0,
    MatOct:0,
    MatNov:0,
    MatDec:0,
    MatYtdTotal:0,
    MatLbe:0,
    MatYtdVarianceToBudget:0,
    MatVarianceToBudget:0
},
{
    ListName: 'FinanceAppMaterialData',
    ItemId: 2,
    Year: 2017,
    State: 'create',
    Highlights: [],   
    Mat:'<PLACEHOLDER>',
    MatBudget: 0,
    MatJan: 0,
    MatFeb:0,
    MatMar:0,
    MatApr:0,
    MatMay:0,
    MatJun:0,
    MatJul:0,
    MatAug:0,
    MatSep:0,
    MatOct:0,
    MatNov:0,
    MatDec:0,
    MatYtdTotal:0,
    MatLbe:0,
    MatYtdVarianceToBudget:0,
    MatVarianceToBudget:0
}  
]