import { ITotalModel } from '../model/total.model'
export const initTotalData:ITotalModel[] = [
    {
        ListName: 'FinanceAppTotalsData',
        ItemId: 1,
        Year: 2017,
        State: 'create',
        Highlights: [],
        Placeholder1:'TOTAL (Incl Resource Costs)',
        PRBudget:0,
        PRJan: 0,
        PRFeb:0,
        PRMar: 0,
        PRApr: 0,
        PRMay: 0,
        PRJun: 0,
        PRJul: 0,
        PRAug: 0,
        PRSep: 0,
        PROct: 0,
        PRNov: 0,
        PRDec: 0,
        PRYtdTotal: 0,
        PRLbe: 0,
        PRYtdVarianceToBudget: 0,
        PRForecastVarianceToBudget: 0,
        RTSBudget: 0,
        RTSJan: 0,
        RTSFeb: 0,
        RTSMar: 0,
        RTSApr: 0,
        RTSMay: 0,
        RTSJun: 0,
        RTSJul: 0,
        RTSAug: 0,
        RTSSep: 0,
        RTSOct: 0,
        RTSNov: 0,
        RTSDec: 0,
        RTSYtdTotal: 0,
        RTSLbe: 0,
        RTSYtdVarianceToBudget: 0,
        RTSVarianceToBudget: 0,
        MatBudget: 0,
        MatJan: 0,
        MatFeb: 0,
        MatMar: 0,
        MatApr: 0,
        MatMay: 0,
        MatJun: 0,
        MatJul: 0,
        MatAug: 0,
        MatSep: 0,
        MatOct: 0,
        MatNov: 0,
        MatDec: 0,
        MatYtdTotal: 0,
        MatLbe: 0,
        MatYtdVarianceToBudget: 0,
        MatForecastVarianceToBudget: 0,        
        TProjectBudget:0,
        TJan:0,
        TFeb:0,
        TMar:0,
        TApr:0,
        TMay:0,
        TJun:0,
        TJul:0,
        TAug:0,
        TSep:0,
        TOct:0,
        TNov:0,
        TDec:0,
        TYtdTotal:0,
        TLbe:0,
        TYtdVarianceToBudget:0,
        TVarianceToBudget:0,
        Placeholder4: 'Resource Totals',
        Placeholder5: 'Resource T&S Totals',
        Placeholder6: 'Material Totals'
    }
]
